### Get Package
# 读取包信息
GET {{SAP_URL}}/sap/bc/adt/packages/{{PACKAGE_NAME}}?sap-client={{SAP_CLIENT}}
Authorization: Basic {{SAP_USER}}:{{SAP_PASSWORD}}
Accept: application/vnd.sap.adt.packages.v2+xml, application/vnd.sap.adt.packages.v1+xml
X-sap-adt-profiling: server-time

### Get Package with Cache
# 使用 ETag 缓存读取包信息
GET {{SAP_URL}}/sap/bc/adt/packages/{{PACKAGE_NAME}}?sap-client={{SAP_CLIENT}}
Authorization: Basic {{SAP_USER}}:{{SAP_PASSWORD}}
Accept: application/vnd.sap.adt.packages.v2+xml, application/vnd.sap.adt.packages.v1+xml
If-None-Match: {{etag}}
X-sap-adt-profiling: server-time

### Get Package Properties
# 获取包对象属性
GET {{SAP_URL}}/sap/bc/adt/repository/informationsystem/objectproperties/values?sap-client={{SAP_CLIENT}}
Authorization: Basic {{SAP_USER}}:{{SAP_PASSWORD}}
Accept: application/vnd.sap.adt.repository.objproperties.result.v1+xml
X-sap-adt-profiling: server-time
&uri=%2Fsap%2Fbc%2Fadt%2Fpackages%2F{{PACKAGE_NAME}}

### Validate Package (Basic)
# 基本验证 - 快速检查
POST {{SAP_URL}}/sap/bc/adt/packages/validation?sap-client={{SAP_CLIENT}}
Authorization: Basic {{SAP_USER}}:{{SAP_PASSWORD}}
Accept: application/vnd.sap.as+xml
X-sap-adt-profiling: server-time
Content-Type: application/x-www-form-urlencoded

objname={{PACKAGE_NAME}}&description={{PACKAGE_DESCRIPTION}}&packagetype={{PACKAGE_TYPE}}&swcomp={{SOFTWARE_COMPONENT}}&checkmode=basic

### Validate Package (Full)
# 完整验证 - 详细检查
POST {{SAP_URL}}/sap/bc/adt/packages/validation?sap-client={{SAP_CLIENT}}
Authorization: Basic {{SAP_USER}}:{{SAP_PASSWORD}}
Accept: application/vnd.sap.as+xml
X-sap-adt-profiling: server-time
Content-Type: application/x-www-form-urlencoded

objname={{PACKAGE_NAME}}&description={{PACKAGE_DESCRIPTION}}&packagetype={{PACKAGE_TYPE}}&swcomp={{SOFTWARE_COMPONENT}}&appcomp={{APPLICATION_COMPONENT}}&checkmode=full

### Get Transport Layers
# 获取传输层列表（值帮助）
GET {{SAP_URL}}/sap/bc/adt/packages/valuehelps/transportlayers?sap-client={{SAP_CLIENT}}
Authorization: Basic {{SAP_USER}}:{{SAP_PASSWORD}}
Accept: application/xml, application/vnd.sap.adt.nameditems.v1+xml
X-sap-adt-profiling: server-time
&name={{NAME_PATTERN}}

### Get Software Components
# 获取软件组件列表（值帮助）
GET {{SAP_URL}}/sap/bc/adt/packages/valuehelps/softwarecomponents?sap-client={{SAP_CLIENT}}
Authorization: Basic {{SAP_USER}}:{{SAP_PASSWORD}}
Accept: application/xml, application/vnd.sap.adt.nameditems.v1+xml
X-sap-adt-profiling: server-time
&name={{NAME_PATTERN}}

### Get Translation Relevances
# 获取翻译相关性列表（值帮助）
GET {{SAP_URL}}/sap/bc/adt/packages/valuehelps/translationrelevances?sap-client={{SAP_CLIENT}}
Authorization: Basic {{SAP_USER}}:{{SAP_PASSWORD}}
Accept: application/xml, application/vnd.sap.adt.nameditems.v1+xml
X-sap-adt-profiling: server-time
&maxItemCount={{MAX_ITEM_COUNT}}

### Create Package
# 创建新包
POST {{SAP_URL}}/sap/bc/adt/packages?corrNr={{TRANSPORT_REQUEST}}&sap-client={{SAP_CLIENT}}
Authorization: Basic {{SAP_USER}}:{{SAP_PASSWORD}}
Content-Type: application/vnd.sap.adt.packages.v1+xml
Accept: application/vnd.sap.adt.packages.v2+xml, application/vnd.sap.adt.packages.v1+xml
X-sap-adt-profiling: server-time

<?xml version="1.0" encoding="UTF-8"?>
<package:package xmlns:package="http://www.sap.com/adt/packages">
  <package:name>{{PACKAGE_NAME}}</package:name>
  <package:description>{{PACKAGE_DESCRIPTION}}</package:description>
  <package:packageType>{{PACKAGE_TYPE}}</package:packageType>
  <package:softwareComponent>{{SOFTWARE_COMPONENT}}</package:softwareComponent>
  <package:transportLayer>{{TRANSPORT_LAYER}}</package:transportLayer>
  <package:applicationComponent>{{APPLICATION_COMPONENT}}</package:applicationComponent>
  <package:responsible>{{RESPONSIBLE}}</package:responsible>
</package:package>

### Create Package (Minimal)
# 创建包 - 最小配置
POST {{SAP_URL}}/sap/bc/adt/packages?corrNr={{TRANSPORT_REQUEST}}&sap-client={{SAP_CLIENT}}
Authorization: Basic {{SAP_USER}}:{{SAP_PASSWORD}}
Content-Type: application/vnd.sap.adt.packages.v1+xml
Accept: application/vnd.sap.adt.packages.v2+xml, application/vnd.sap.adt.packages.v1+xml
X-sap-adt-profiling: server-time

<?xml version="1.0" encoding="UTF-8"?>
<package:package xmlns:package="http://www.sap.com/adt/packages">
  <package:name>{{PACKAGE_NAME}}</package:name>
  <package:description>{{PACKAGE_DESCRIPTION}}</package:description>
  <package:packageType>development</package:packageType>
  <package:softwareComponent>HOME</package:softwareComponent>
  <package:transportLayer>ZSAP</package:transportLayer>
</package:package>
