# PACKAGE_NAME API Settings
@PACKAGE_NAME={{$dotenv PACKAGE_NAME}}
@PACKAGE_NAME_DESCRIPTION=My PACKAGE_NAME Description
@PACKAGE_NAME_TYPE=development
@SOFTWARE_COMPONENT=HOME
@APPLICATION_COMPONENT=HOME
@TRANSPORT_LAYER=ZSAP
@RESPONSIBLE={{$dotenv SAP_USER}}
@TRANSPORT_REQUEST=S4HK901712
@baseUrl = {{$dotenv SAP_URL}}
@user = {{$dotenv SAP_USER}}
@password = {{$dotenv SAP_PASSWORD}}
@client = {{$dotenv SAP_CLIENT}}
@NAME_PATTERN={{$dotenv NAME_PATTERN}}



### Get PACKAGE_NAME
# 读取包信息
GET {{baseUrl}}/sap/bc/adt/packages/{{PACKAGE_NAME}}?sap-client={{client}}
Authorization: Basic {{user}}:{{password}}
Accept: application/vnd.sap.adt.packages.v2+xml, application/vnd.sap.adt.packages.v1+xml
X-sap-adt-profiling: server-time

### Get PACKAGE_NAME with Cache
# 使用 ETag 缓存读取包信息
GET {{baseUrl}}/sap/bc/adt/packages/{{PACKAGE_NAME}}?sap-client={{client}}
Authorization: Basic {{user}}:{{password}}
Accept: application/vnd.sap.adt.packages.v2+xml, application/vnd.sap.adt.packages.v1+xml
If-None-Match: {{etag}}
X-sap-adt-profiling: server-time

### Get PACKAGE_NAME Properties
# 获取包对象属性
GET {{baseUrl}}/sap/bc/adt/repository/informationsystem/objectproperties/values?sap-client={{client}}
Authorization: Basic {{user}}:{{password}}
Accept: application/vnd.sap.adt.repository.objproperties.result.v1+xml
X-sap-adt-profiling: server-time

### Validate PACKAGE_NAME (Basic)
# 基本验证 - 快速检查
POST {{baseUrl}}/sap/bc/adt/packages/validation?sap-client={{client}}
Authorization: Basic {{user}}:{{password}}
Accept: application/vnd.sap.as+xml
X-sap-adt-profiling: server-time
Content-Type: application/x-www-form-urlencoded

objname={{PACKAGE_NAME}}&description={{PACKAGE_NAME_DESCRIPTION}}&PACKAGE_NAMEtype={{PACKAGE_NAME_TYPE}}&swcomp={{SOFTWARE_COMPONENT}}&checkmode=basic

### Validate PACKAGE_NAME (Full)
# 完整验证 - 详细检查
POST {{baseUrl}}/sap/bc/adt/packages/validation?sap-client={{client}}
Authorization: Basic {{user}}:{{password}}
Accept: application/vnd.sap.as+xml
X-sap-adt-profiling: server-time
Content-Type: application/x-www-form-urlencoded

objname={{PACKAGE_NAME}}&description={{PACKAGE_NAME_DESCRIPTION}}&PACKAGE_NAMEtype={{PACKAGE_NAME_TYPE}}&swcomp={{SOFTWARE_COMPONENT}}&appcomp={{APPLICATION_COMPONENT}}&checkmode=full

### Get Transport Layers
# 获取传输层列表（值帮助）
GET {{baseUrl}}/sap/bc/adt/packages/valuehelps/transportlayers?sap-client={{client}}
Authorization: Basic {{user}}:{{password}}
Accept: application/xml, application/vnd.sap.adt.nameditems.v1+xml
X-sap-adt-profiling: server-time
name:{{NAME_PATTERN}}

### Get Software Components
# 获取软件组件列表（值帮助）
GET {{baseUrl}}/sap/bc/adt/packages/valuehelps/softwarecomponents?sap-client={{client}}
Authorization: Basic {{user}}:{{password}}
Accept: application/xml, application/vnd.sap.adt.nameditems.v1+xml
X-sap-adt-profiling: server-time
name: {{NAME_PATTERN}}

### Get Translation Relevances
# 获取翻译相关性列表（值帮助）
GET {{baseUrl}}/sap/bc/adt/packages/valuehelps/translationrelevances?sap-client={{client}}
Authorization: Basic {{user}}:{{password}}
Accept: application/xml, application/vnd.sap.adt.nameditems.v1+xml
X-sap-adt-profiling: server-time
maxItemCount: 100

### Create PACKAGE_NAME
# 创建新包
POST {{baseUrl}}/sap/bc/adt/packages?corrNr={{TRANSPORT_REQUEST}}&sap-client={{client}}
Authorization: Basic {{user}}:{{password}}
Content-Type: application/vnd.sap.adt.packages.v1+xml
Accept: application/vnd.sap.adt.packages.v2+xml, application/vnd.sap.adt.packages.v1+xml
X-sap-adt-profiling: server-time

<?xml version="1.0" encoding="UTF-8"?>
<PACKAGE_NAME:PACKAGE_NAME xmlns:PACKAGE_NAME="http://www.sap.com/adt/packages">
  <PACKAGE_NAME:name>{{PACKAGE_NAME}}</PACKAGE_NAME:name>
  <PACKAGE_NAME:description>{{PACKAGE_NAME_DESCRIPTION}}</PACKAGE_NAME:description>
  <PACKAGE_NAME:PACKAGE_NAMEType>{{PACKAGE_NAME_TYPE}}</PACKAGE_NAME:PACKAGE_NAMEType>
  <PACKAGE_NAME:softwareComponent>{{SOFTWARE_COMPONENT}}</PACKAGE_NAME:softwareComponent>
  <PACKAGE_NAME:transportLayer>{{TRANSPORT_LAYER}}</PACKAGE_NAME:transportLayer>
  <PACKAGE_NAME:applicationComponent>{{APPLICATION_COMPONENT}}</PACKAGE_NAME:applicationComponent>
  <PACKAGE_NAME:responsible>{{RESPONSIBLE}}</PACKAGE_NAME:responsible>
</PACKAGE_NAME:PACKAGE_NAME>

### Create PACKAGE_NAME (Minimal)
# 创建包 - 最小配置
POST {{baseUrl}}/sap/bc/adt/packages?corrNr={{TRANSPORT_REQUEST}}&sap-client={{client}}
Authorization: Basic {{user}}:{{password}}
Content-Type: application/vnd.sap.adt.packages.v1+xml
Accept: application/vnd.sap.adt.packages.v2+xml, application/vnd.sap.adt.packages.v1+xml
X-sap-adt-profiling: server-time

<?xml version="1.0" encoding="UTF-8"?>
<PACKAGE_NAME:PACKAGE_NAME xmlns:PACKAGE_NAME="http://www.sap.com/adt/packages">
  <PACKAGE_NAME:name>{{PACKAGE_NAME}}</PACKAGE_NAME:name>
  <PACKAGE_NAME:description>{{PACKAGE_NAME_DESCRIPTION}}</PACKAGE_NAME:description>
  <PACKAGE_NAME:PACKAGE_NAMEType>development</PACKAGE_NAME:PACKAGE_NAMEType>
  <PACKAGE_NAME:softwareComponent>HOME</PACKAGE_NAME:softwareComponent>
  <PACKAGE_NAME:transportLayer>ZSAP</PACKAGE_NAME:transportLayer>
</PACKAGE_NAME:PACKAGE_NAME>
